# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nodes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/nodes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/nodes.proto\x12\x05\x63loud\".\n\x0bNodeRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x11\n\tnode_type\x18\x02 \x01(\t\"/\n\x0cNodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t2D\n\x0bNodeService\x12\x35\n\nCreateNode\x12\x12.cloud.NodeRequest\x1a\x13.cloud.NodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nodes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEREQUEST']._serialized_start=28
  _globals['_NODEREQUEST']._serialized_end=74
  _globals['_NODERESPONSE']._serialized_start=76
  _globals['_NODERESPONSE']._serialized_end=123
  _globals['_NODESERVICE']._serialized_start=125
  _globals['_NODESERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
